### ISSUE TITLE
Manual for SILE 0.14.2 not found (404)

### ISSUE THREAD

**Issue by jmaibaum** [sile-typesetter/sile-typesetter.github.io#36]
The [Manual (PDF)](https://sile-typesetter.org/manual/sile-0.14.2.pdf) link in the sidebar raises a 404 for the 0.14.2 PDF manual.

**Comment by alerque** [comment]
Thanks for the report! I seem to have uploaded the latest manual to the examples directory instead of the manual directory. I don't know how that happened but I'll fix it now.
