### ISSUE TITLE
Manual link 404s

### ISSUE THREAD

**Issue by horo-fox** [sile-typesetter/sile-typesetter.github.io#43]
<https://sile-typesetter.org/manual/sile-0.15.3.pdf> 404s which is the link on <https://sile-typesetter.org/>. <https://sile-typesetter.org/manual/sile-0.15.2.pdf> works though.

**Comment by alerque** [comment]
Thanks for the report. This should be fixed by 1726929. It looks like I neglected to `git add` the PDF to the original commit that updated the links.
